Airports/Controllers/AirportController.cs
using Airports.Base.ViewModels;
using Airports.Base.Filters;
using Airports.BLL.Managers;
using PagedList;
using System.Web.Mvc;
using Airports.Base.DBModels;
using Airports.Base.Exceptions;

namespace Airports.Controllers
{
    [JsonFeedHeader]
    public class AirportController : BaseController
    {
        #region ctors

        private readonly IAirportManager _airportManager;
        public AirportController(IAirportManager airportManager)
        {
            _airportManager = airportManager;
        }

        #endregion

        #region actions 

        
        public ActionResult Index(AirportFilter filter)
        {
            PoulateViewBag(filter);

            var airportPaged = _airportManager.FindAirports(filter);
            return View(new StaticPagedList<AirportViewModel>(airportPaged.Airports, filter.Page, filter.PageSize, airportPaged.TotalItems));
        }

        [Route("calculate")]
        public ActionResult Calculate(string from, string to)
        {
            return Json(new Response<DistanceViewModel>(_airportManager.CalculateDistance(from, to)));
        }

        [Route("distance")]
        public ActionResult Distance(string from, string to)
        {
            try
            {
                return View("Distance", _airportManager.CalculateDistance(from, to));
            }
            catch (AirportException)
            {
                return View("Distance", new DistanceViewModel(0, new Airport(from), new Airport(to)) { Message = "Please provide correct IATAs!"});
            }
        }

        #endregion

        #region helpers

        private void PoulateViewBag(AirportFilter filter)
        {
            ViewBag.Continent = filter.Continent;
            ViewBag.ISO = filter.ISO;
            ViewBag.Size = filter.Size;
            ViewBag.Type = filter.Type;
            ViewBag.Name = filter.Name;
        }

        #endregion
    }
}

Airports/Controllers/BaseController.cs
using Airports.AspMvcConfigs;
using System.Text;
using System.Web.Mvc;

namespace Airports.Controllers
{
    public class BaseController : Controller
    {
        protected override JsonResult Json(object data, string contentType, Encoding contentEncoding, JsonRequestBehavior behavior)
        {
            return new JsonDotNetResult
            {
                Data = data,
                ContentType = contentType,
                ContentEncoding = contentEncoding,
                JsonRequestBehavior = behavior
            };
        }
    }
}

Airports/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace Airports.Controllers
{
    public class ErrorController: Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Regular Error";
            return View();
        }
    }
}

Airports/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airports.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Airports/Views/Airport/Distance.cshtml
@model Airports.Base.ViewModels.DistanceViewModel

@{
    ViewBag.Title = "Distance";
}

<h2>Airports</h2>
<div id="distance">
    @if (!string.IsNullOrEmpty(Model.Message))
    {
        @Model.Message
    }
    else
    {
        <span>
            The distance from<b>@Html.DisplayFor(m => m.From)</b> to <b>@Html.DisplayFor(m => m.To)</b> is <b>@Html.DisplayFor(m => m.Distance)</b>km
        </span>
    }
</div>

Airports/Views/Airport/Index.cshtml
@model PagedList.IPagedList<AirportViewModel>
@using PagedList.Mvc;
@using Airports.Base.ViewModels;
@using Airports.Base.Enums;

@{
    ViewBag.Title = "Airports";
}

<h2>Airports</h2>

<div>
    <p>
        Link for distance calculations: "http://ovasylenko.net/Airport/Distance?from=<b>fromIATA</b>&to=<b>toIATA</b>"
    </p>
    <p>
        From: @Html.TextBox("From", ViewBag.From as string, new { id = "txtFrom" })
        To: @Html.TextBox("To", ViewBag.To as string, new { id = "txtTo" })
        <input id="calculateDistance" type="button" value="Calculate" />
    </p>
    <p id="distance">
        The distance from <b id="spFrom"></b> to <b id="spTo"></b> is <b id="spDist"></b> km
    </p>
    <hr />
</div>

@using (Html.BeginForm("Index", "Airport", FormMethod.Get))
{
    <div class="row top-buff-10">
        <div class="col-md-2">
            ISO or Country Name
        </div>
        <div class="col-md-10">
            @Html.TextBox("iso", ViewBag.ISO as string)
        </div>
    </div>
    <div class="row top-buff-10">
        <div class="col-md-2">
            Name
        </div>
        <div class="col-md-10">
            @Html.TextBox("name", ViewBag.Name as string)
        </div>
    </div>
    <div class="row top-buff-10">
        <div class="col-md-2">
            Continent
        </div>
        <div class="col-md-10">
            @Html.DropDownList("continent", EnumHelper.GetSelectList(typeof(AirportContinent)), new { @id = "ddContinents" })
        </div>
    </div>
    <div class="row top-buff-10">
        <div class="col-md-2">
            Size
        </div>
        <div class="col-md-10">
            @Html.DropDownList("size", EnumHelper.GetSelectList(typeof(AirportSize)), new { @id = "ddAirportSize" })
        </div>
    </div>
    <div class="row top-buff-10">
        <div class="col-md-2">
            Type
        </div>
        <div class="col-md-10">
            @Html.DropDownList("type", EnumHelper.GetSelectList(typeof(AirportType)), new { @id = "ddAirportType" })
        </div>
    </div>
    <input class="top-buff-10" type="submit" value="Search" />
}
<div class="row top-buff-10">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>
                    @(Html.LabelFor<PagedList.IPagedList<AirportViewModel>, string>(m => m.FirstOrDefault().IATA))
                </th>
                <th>
                    @(Html.LabelFor<PagedList.IPagedList<AirportViewModel>, string>(m => m.FirstOrDefault().ISO))
                </th>
                <th>
                    @(Html.LabelFor<PagedList.IPagedList<AirportViewModel>, string>(m => m.FirstOrDefault().Country))
                </th>
                <th>
                    @(Html.LabelFor<PagedList.IPagedList<AirportViewModel>, string>(m => m.FirstOrDefault().Name))
                </th>
                <th>
                    @(Html.LabelFor<PagedList.IPagedList<AirportViewModel>, AirportContinent>(m => m.FirstOrDefault().Continent))
                </th>
                <th>
                    @(Html.LabelFor<PagedList.IPagedList<AirportViewModel>, AirportType>(m => m.FirstOrDefault().Type))
                </th>
                <th>
                    @(Html.LabelFor<PagedList.IPagedList<AirportViewModel>, AirportSize>(m => m.FirstOrDefault().Size))
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IATA)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ISO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Country)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Continent)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Size)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, type = ViewBag.Type, size = ViewBag.Size, continent = ViewBag.Continent, name = ViewBag.Name, iso = ViewBag.ISO, }))

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#distance").hide();
            setDDls();

            $('#calculateDistance').click(function () {
                var from = $("#txtFrom").val();
                var to = $("#txtTo").val();
                var href = "@Url.Action("Calculate", "Airport")" + "?from=" + from + "&to=" + to;

                $.ajax({
                    type: "post",
                    url: href,
                    success: function (resp) {
                        if (resp.success)
                            showDistance(resp.data)
                        else
                            alert(resp.message);
                    }
                });
            });

            function showDistance(data) {
                $("#distance").show();

                $('#spFrom').html(data.from);
                $('#spTo').html(data.to);
                $('#spDist').html(data.distance);
            }

            function setDDls() {
                $("#ddContinents").val(@((int?)ViewBag.Continent));
                $("#ddAirportSize").val(@((int?)ViewBag.Size));
                $("#ddAirportType").val(@((int?)ViewBag.Type));
            }
        });
    </script>
}

Airports/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Airports/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Airports/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Airports/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Airports", "Index", "Airport")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>